export default {
  progress: 'awsui_progress_11huc_fnv5f_357',
  'result-state': 'awsui_result-state_11huc_fnv5f_371',
  'awsui-motion-fade-in': 'awsui_awsui-motion-fade-in_11huc_fnv5f_1',
  root: 'awsui_root_11huc_fnv5f_393',
  'with-result-button': 'awsui_with-result-button_11huc_fnv5f_428',
  'result-text': 'awsui_result-text_11huc_fnv5f_432',
  'result-container-error': 'awsui_result-container-error_11huc_fnv5f_436',
  'result-container-success': 'awsui_result-container-success_11huc_fnv5f_436',
  'result-button': 'awsui_result-button_11huc_fnv5f_440',
  'word-wrap': 'awsui_word-wrap_11huc_fnv5f_446',
  'label-flash': 'awsui_label-flash_11huc_fnv5f_451',
  'label-key-value': 'awsui_label-key-value_11huc_fnv5f_455',
  flash: 'awsui_flash_11huc_fnv5f_463',
  'progress-container': 'awsui_progress-container_11huc_fnv5f_467',
  'percentage-container': 'awsui_percentage-container_11huc_fnv5f_474',
  percentage: 'awsui_percentage_11huc_fnv5f_474',
  complete: 'awsui_complete_11huc_fnv5f_520',
  'progress-in-flash': 'awsui_progress-in-flash_11huc_fnv5f_548',
  'additional-info': 'awsui_additional-info_11huc_fnv5f_564'
}
