export default {
  background: 'awsui_background_hyvsj_r2ruh_147',
  'scrolling-background': 'awsui_scrolling-background_hyvsj_r2ruh_150',
  breadcrumbs: 'awsui_breadcrumbs_hyvsj_r2ruh_161',
  'drawers-container': 'awsui_drawers-container_hyvsj_r2ruh_174',
  'has-open-drawer': 'awsui_has-open-drawer_hyvsj_r2ruh_185',
  'disable-body-scroll': 'awsui_disable-body-scroll_hyvsj_r2ruh_208',
  'drawers-desktop-triggers-container':
    'awsui_drawers-desktop-triggers-container_hyvsj_r2ruh_213',
  'has-multiple-triggers': 'awsui_has-multiple-triggers_hyvsj_r2ruh_254',
  'drawers-mobile-triggers-container':
    'awsui_drawers-mobile-triggers-container_hyvsj_r2ruh_264',
  'drawers-trigger-content': 'awsui_drawers-trigger-content_hyvsj_r2ruh_268',
  'drawers-trigger-overflow': 'awsui_drawers-trigger-overflow_hyvsj_r2ruh_282',
  'drawers-trigger': 'awsui_drawers-trigger_hyvsj_r2ruh_268',
  drawer: 'awsui_drawer_hyvsj_r2ruh_174',
  'drawer-content-container': 'awsui_drawer-content-container_hyvsj_r2ruh_313',
  'drawer-close-button': 'awsui_drawer-close-button_hyvsj_r2ruh_322',
  'drawer-content': 'awsui_drawer-content_hyvsj_r2ruh_313',
  'drawer-content-hidden': 'awsui_drawer-content-hidden_hyvsj_r2ruh_330',
  'drawer-slider': 'awsui_drawer-slider_hyvsj_r2ruh_333',
  'is-drawer-open': 'awsui_is-drawer-open_hyvsj_r2ruh_340',
  content: 'awsui_content_hyvsj_r2ruh_366',
  layout: 'awsui_layout_hyvsj_r2ruh_391',
  'has-max-content-width': 'awsui_has-max-content-width_hyvsj_r2ruh_464',
  'content-type-dashboard': 'awsui_content-type-dashboard_hyvsj_r2ruh_479',
  'content-type-table': 'awsui_content-type-table_hyvsj_r2ruh_493',
  'content-type-cards': 'awsui_content-type-cards_hyvsj_r2ruh_493',
  'is-overlap-disabled': 'awsui_is-overlap-disabled_hyvsj_r2ruh_499',
  'is-hide-mobile-toolbar': 'awsui_is-hide-mobile-toolbar_hyvsj_r2ruh_502',
  'has-content-gap-left': 'awsui_has-content-gap-left_hyvsj_r2ruh_516',
  'has-content-gap-right': 'awsui_has-content-gap-right_hyvsj_r2ruh_519',
  'has-breadcrumbs': 'awsui_has-breadcrumbs_hyvsj_r2ruh_529',
  'content-first-child-header':
    'awsui_content-first-child-header_hyvsj_r2ruh_532',
  'content-first-child-notifications':
    'awsui_content-first-child-notifications_hyvsj_r2ruh_532',
  'has-header': 'awsui_has-header_hyvsj_r2ruh_532',
  'content-first-child-main': 'awsui_content-first-child-main_hyvsj_r2ruh_547',
  'disable-content-paddings': 'awsui_disable-content-paddings_hyvsj_r2ruh_547',
  'has-left-toggles-gutter': 'awsui_has-left-toggles-gutter_hyvsj_r2ruh_567',
  'has-right-toggles-gutter': 'awsui_has-right-toggles-gutter_hyvsj_r2ruh_570',
  'has-split-panel': 'awsui_has-split-panel_hyvsj_r2ruh_590',
  'split-panel-position-bottom':
    'awsui_split-panel-position-bottom_hyvsj_r2ruh_590',
  'block-body-scroll': 'awsui_block-body-scroll_hyvsj_r2ruh_598',
  unfocusable: 'awsui_unfocusable_hyvsj_r2ruh_603',
  container: 'awsui_container_hyvsj_r2ruh_613',
  'is-navigation-open': 'awsui_is-navigation-open_hyvsj_r2ruh_639',
  'is-tools-open': 'awsui_is-tools-open_hyvsj_r2ruh_642',
  'is-split-panel-open': 'awsui_is-split-panel-open_hyvsj_r2ruh_642',
  'split-panel-position-side':
    'awsui_split-panel-position-side_hyvsj_r2ruh_642',
  'has-active-drawer': 'awsui_has-active-drawer_hyvsj_r2ruh_642',
  'mobile-toolbar': 'awsui_mobile-toolbar_hyvsj_r2ruh_651',
  'remove-high-contrast-header':
    'awsui_remove-high-contrast-header_hyvsj_r2ruh_668',
  'mobile-toolbar-nav': 'awsui_mobile-toolbar-nav_hyvsj_r2ruh_672',
  'mobile-toolbar-breadcrumbs':
    'awsui_mobile-toolbar-breadcrumbs_hyvsj_r2ruh_676',
  'mobile-toolbar-tools': 'awsui_mobile-toolbar-tools_hyvsj_r2ruh_680',
  'navigation-container': 'awsui_navigation-container_hyvsj_r2ruh_689',
  'show-navigation': 'awsui_show-navigation_hyvsj_r2ruh_727',
  animating: 'awsui_animating_hyvsj_r2ruh_750',
  showButtons: 'awsui_showButtons_hyvsj_r2ruh_1',
  navigation: 'awsui_navigation_hyvsj_r2ruh_689',
  openNavigation: 'awsui_openNavigation_hyvsj_r2ruh_1',
  'animated-content': 'awsui_animated-content_hyvsj_r2ruh_812',
  'hide-navigation': 'awsui_hide-navigation_hyvsj_r2ruh_821',
  notifications: 'awsui_notifications_hyvsj_r2ruh_831',
  'has-notification-content': 'awsui_has-notification-content_hyvsj_r2ruh_836',
  'sticky-notifications': 'awsui_sticky-notifications_hyvsj_r2ruh_840',
  'high-contrast': 'awsui_high-contrast_hyvsj_r2ruh_845',
  'split-panel-bottom': 'awsui_split-panel-bottom_hyvsj_r2ruh_863',
  'position-bottom': 'awsui_position-bottom_hyvsj_r2ruh_910',
  openSplitPanelBottom: 'awsui_openSplitPanelBottom_hyvsj_r2ruh_1',
  'split-panel-side': 'awsui_split-panel-side_hyvsj_r2ruh_939',
  'position-side': 'awsui_position-side_hyvsj_r2ruh_952',
  'tools-container': 'awsui_tools-container_hyvsj_r2ruh_974',
  tools: 'awsui_tools_hyvsj_r2ruh_974',
  openTools: 'awsui_openTools_hyvsj_r2ruh_1',
  'has-tools-form-persistence':
    'awsui_has-tools-form-persistence_hyvsj_r2ruh_1065',
  'hide-tools': 'awsui_hide-tools_hyvsj_r2ruh_1075',
  'show-tools': 'awsui_show-tools_hyvsj_r2ruh_1087',
  'has-tools-form': 'awsui_has-tools-form_hyvsj_r2ruh_1065',
  'trigger-badge-wrapper': 'awsui_trigger-badge-wrapper_hyvsj_r2ruh_1170',
  trigger: 'awsui_trigger_hyvsj_r2ruh_1170',
  selected: 'awsui_selected_hyvsj_r2ruh_1247',
  badge: 'awsui_badge_hyvsj_r2ruh_1267',
  'trigger-wrapper': 'awsui_trigger-wrapper_hyvsj_r2ruh_1271',
  dot: 'awsui_dot_hyvsj_r2ruh_1282'
}
