export default {
  'icon-shake': 'awsui_icon-shake_1cbgc_wdg8f_147',
  'awsui-motion-shake-horizontally':
    'awsui_awsui-motion-shake-horizontally_1cbgc_wdg8f_1',
  'container-fade-in': 'awsui_container-fade-in_1cbgc_wdg8f_175',
  'awsui-motion-fade-in-0': 'awsui_awsui-motion-fade-in-0_1cbgc_wdg8f_1',
  root: 'awsui_root_1cbgc_wdg8f_197',
  'status-error': 'awsui_status-error_1cbgc_wdg8f_206',
  'status-warning': 'awsui_status-warning_1cbgc_wdg8f_209',
  'status-success': 'awsui_status-success_1cbgc_wdg8f_212',
  'status-info': 'awsui_status-info_1cbgc_wdg8f_215',
  'status-stopped': 'awsui_status-stopped_1cbgc_wdg8f_218',
  'status-pending': 'awsui_status-pending_1cbgc_wdg8f_221',
  'status-in-progress': 'awsui_status-in-progress_1cbgc_wdg8f_224',
  'status-loading': 'awsui_status-loading_1cbgc_wdg8f_227',
  'color-override-red': 'awsui_color-override-red_1cbgc_wdg8f_230',
  'color-override-grey': 'awsui_color-override-grey_1cbgc_wdg8f_233',
  'color-override-blue': 'awsui_color-override-blue_1cbgc_wdg8f_236',
  'color-override-green': 'awsui_color-override-green_1cbgc_wdg8f_239',
  'color-override-yellow': 'awsui_color-override-yellow_1cbgc_wdg8f_242',
  container: 'awsui_container_1cbgc_wdg8f_175',
  'display-inline': 'awsui_display-inline_1cbgc_wdg8f_246',
  icon: 'awsui_icon_1cbgc_wdg8f_147',
  'display-inline-block': 'awsui_display-inline-block_1cbgc_wdg8f_254',
  'overflow-ellipsis': 'awsui_overflow-ellipsis_1cbgc_wdg8f_263'
}
