export default {
  'preference-icon--svg': 'awsui_preference-icon--svg_d4xxm_1qs6h_143',
  'preference-icon--layout-border':
    'awsui_preference-icon--layout-border_d4xxm_1qs6h_146',
  'preference-icon--layout-background':
    'awsui_preference-icon--layout-background_d4xxm_1qs6h_150',
  'preference-icon--layout-header':
    'awsui_preference-icon--layout-header_d4xxm_1qs6h_153',
  'preference-icon--border': 'awsui_preference-icon--border_d4xxm_1qs6h_156',
  'preference-icon--primary-button':
    'awsui_preference-icon--primary-button_d4xxm_1qs6h_160',
  'preference-icon--secondary':
    'awsui_preference-icon--secondary_d4xxm_1qs6h_163',
  'preference-icon--disabled-element':
    'awsui_preference-icon--disabled-element_d4xxm_1qs6h_166',
  'preference-icon--separator':
    'awsui_preference-icon--separator_d4xxm_1qs6h_169',
  'preference-icon--focus-text':
    'awsui_preference-icon--focus-text_d4xxm_1qs6h_172',
  'preference-icon-refresh--svg':
    'awsui_preference-icon-refresh--svg_d4xxm_1qs6h_176',
  'preference-icon-refresh--layout-top':
    'awsui_preference-icon-refresh--layout-top_d4xxm_1qs6h_179',
  'preference-icon-refresh--layout-main':
    'awsui_preference-icon-refresh--layout-main_d4xxm_1qs6h_182',
  'preference-icon-refresh--primary':
    'awsui_preference-icon-refresh--primary_d4xxm_1qs6h_185',
  'preference-icon-refresh--disabled':
    'awsui_preference-icon-refresh--disabled_d4xxm_1qs6h_188',
  'preference-icon-refresh--column-header':
    'awsui_preference-icon-refresh--column-header_d4xxm_1qs6h_191',
  'preference-icon-refresh--window':
    'awsui_preference-icon-refresh--window_d4xxm_1qs6h_194',
  'preference-icon-refresh--secondary':
    'awsui_preference-icon-refresh--secondary_d4xxm_1qs6h_198',
  'preference-icon-refresh--default':
    'awsui_preference-icon-refresh--default_d4xxm_1qs6h_201',
  'preference-icon-refresh--separator':
    'awsui_preference-icon-refresh--separator_d4xxm_1qs6h_204',
  'preference-icon-refresh--input-default':
    'awsui_preference-icon-refresh--input-default_d4xxm_1qs6h_207',
  'preference-icon-refresh--heading':
    'awsui_preference-icon-refresh--heading_d4xxm_1qs6h_210'
}
